-- Migration: Create jobs table
-- Run this migration to add the jobs table to an existing database.

CREATE TABLE IF NOT EXISTS jobs (
  id SERIAL PRIMARY KEY,
  name VARCHAR NULL,
  numberofopenings INTEGER NULL,
  description VARCHAR NULL,
  portalcompanyname VARCHAR NULL,
  portalcity VARCHAR NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  recruiter_update_id INTEGER NULL,
  skills VARCHAR NULL,
  creator_id INTEGER NULL REFERENCES users(id) ON DELETE NO ACTION ON UPDATE NO ACTION,
  pref_skills VARCHAR NULL,
  gen_reqs VARCHAR NULL,
  benefits VARCHAR NULL,
  work_time VARCHAR NULL,
  company_names TEXT NULL,
  school_names TEXT NULL,
  experience_years VARCHAR NULL,
  organization_id UUID NULL,
  leads_count INTEGER NULL DEFAULT 0,
  nice_to_have_skills VARCHAR NULL,
  nice_to_have_keywords VARCHAR NULL,
  keywords VARCHAR NULL,
  notificationemails VARCHAR NULL,
  department VARCHAR[] NULL,
  company_name VARCHAR NULL,
  location VARCHAR NULL,
  referral_amount VARCHAR NULL,
  email_campaign_subject VARCHAR NULL,
  email_campaign_desc VARCHAR NULL,
  sms_campaign_desc VARCHAR NULL,
  location_preference VARCHAR NULL,
  prefered_titles VARCHAR NULL,
  prefered_industries VARCHAR NULL,
  active BOOLEAN NULL DEFAULT true,
  linkedin_url VARCHAR NULL,
  indeed_url VARCHAR NULL,
  campaign_approved BOOLEAN NULL DEFAULT false,
  sync_job BOOLEAN NULL DEFAULT false,
  linkedin_job_id BIGINT NULL DEFAULT 0,
  expiry_date TIMESTAMP NULL,
  referral_candidate BOOLEAN NULL DEFAULT false,
  status INTEGER NULL DEFAULT 0,
  discarded_at TIMESTAMP NULL,
  create_lead BOOLEAN NULL DEFAULT true,
  campaign_status BOOLEAN NULL DEFAULT true,
  hiring_manager_email VARCHAR NULL,
  sourcer_notes VARCHAR[] NULL,
  work_authorization VARCHAR[] NULL,
  compensation VARCHAR[] NULL,
  employment_type VARCHAR[] NULL,
  source_at TIMESTAMP NULL,
  group_id INTEGER NULL,
  boolean_keyword_search VARCHAR NULL,
  job_description_link VARCHAR NULL,
  title_avoid VARCHAR NULL,
  companies_avoid VARCHAR NULL,
  target_location_avoid VARCHAR NULL,
  industry VARCHAR NULL,
  add_notes TEXT NULL,
  upload_files VARCHAR NULL,
  ideal_linked_in_url VARCHAR NULL,
  linkedin_job_url BOOLEAN NULL DEFAULT false,
  mixmax_sequnce_id TEXT NULL,
  mixmax_config_id TEXT NULL,
  manual_sourcing BOOLEAN NULL DEFAULT false,
  tech_group TEXT NULL,
  agency_id INTEGER NULL DEFAULT 0,
  in_mail_message TEXT NULL,
  msg_sequence INTEGER NULL DEFAULT 1,
  reason_to_optout TEXT NULL,
  optout INTEGER NULL DEFAULT 0,
  lead_matched INTEGER NULL DEFAULT 0,
  linkedin_url_2 VARCHAR NULL,
  linkedin_url_3 VARCHAR NULL,
  linkedin_url_4 VARCHAR NULL,
  ai_match INTEGER NULL DEFAULT 0,
  pc_match INTEGER NULL DEFAULT 0,
  match_notification INTEGER NULL DEFAULT 0,
  job_view_type INTEGER NULL DEFAULT 1,
  job_source VARCHAR NULL,
  community_id INTEGER NULL,
  is_original_job INTEGER NULL DEFAULT 0,
  is_automation INTEGER NULL DEFAULT 0,
  automation_limit INTEGER NULL DEFAULT 0,
  last_automation_at TIMESTAMP NULL,
  job_detail_file TEXT NULL,
  job_salary VARCHAR NULL
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_jobs_discarded_at ON jobs(discarded_at);
CREATE INDEX IF NOT EXISTS idx_jobs_recruiter_update_id ON jobs(recruiter_update_id);

-- Trigger for updated_at
DROP TRIGGER IF EXISTS update_jobs_updated_at ON jobs;
CREATE TRIGGER update_jobs_updated_at
  BEFORE UPDATE ON jobs
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();
