-- Migration: Create people, notes, identities tables (referenced by users FK)

-- People table
CREATE TABLE IF NOT EXISTS people (
  id SERIAL PRIMARY KEY,
  first_name VARCHAR NULL,
  last_name VARCHAR NULL,
  formatted_name VARCHAR NULL,
  linkedin_profile_url VARCHAR NULL,
  phone_number VARCHAR NULL,
  search_text VARCHAR NULL,
  keyword VARCHAR NULL,
  location VARCHAR NULL,
  employer VARCHAR NULL,
  title VARCHAR NULL,
  school VARCHAR NULL,
  degree VARCHAR NULL,
  discipline VARCHAR NULL,
  name VARCHAR NULL,
  min_time_in_job INTEGER NULL,
  max_time_in_job INTEGER NULL,
  min_career_length INTEGER NULL,
  max_career_length INTEGER NULL,
  min_activity_date INTEGER NULL,
  max_activity_date INTEGER NULL,
  email_available BOOLEAN NULL,
  linkedin_available BOOLEAN NULL,
  phone_number_available BOOLEAN NULL,
  github_available BOOLEAN NULL,
  top_company_status BOOLEAN NULL,
  linkedin_profile_id_id INTEGER NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  avatar_url VARCHAR NULL,
  linkedin_profile VARCHAR NULL,
  company_position VARCHAR NULL,
  email_address VARCHAR NULL,
  linkedin_field_of_study VARCHAR NULL,
  linkedin_industry VARCHAR NULL,
  linkedin_profile_education VARCHAR NULL,
  linkedin_profile_position VARCHAR NULL,
  linkedin_profile_publication VARCHAR NULL,
  linkedin_profile_recommendation TEXT NULL,
  linkedin_profile_url_resource VARCHAR NULL,
  linkedin_school VARCHAR NULL,
  active BOOLEAN NULL,
  user_id INTEGER NULL,
  note_id INTEGER NULL,
  flag BOOLEAN NULL,
  crelate_id VARCHAR NULL,
  created_by_id VARCHAR NULL,
  modified_on TIMESTAMP NULL,
  updated_by_id VARCHAR NULL,
  created_on TIMESTAMP NULL,
  salary INTEGER NULL,
  salutation VARCHAR NULL,
  icon_attachment_id VARCHAR NULL,
  primary_document_attachment_id VARCHAR NULL,
  nickname VARCHAR NULL,
  account_id VARCHAR NULL,
  contact_number VARCHAR NULL,
  twitter_name VARCHAR NULL,
  contact_source_id VARCHAR NULL,
  middle_name VARCHAR NULL,
  suffix_id VARCHAR NULL,
  ethnicity_id VARCHAR NULL,
  gender_id VARCHAR NULL,
  preferred_contact_method_type_id VARCHAR NULL,
  last_activity_regarding_id VARCHAR NULL,
  last_activity_regarding_id_type VARCHAR NULL,
  last_activity_date TIMESTAMP NULL,
  spoken_to VARCHAR NULL,
  contact_status_id VARCHAR NULL,
  contact_merge_id VARCHAR NULL,
  approve_for_job_id VARCHAR NULL,
  salary_details VARCHAR NULL,
  record_type VARCHAR NULL,
  description VARCHAR NULL,
  created_on_system TIMESTAMP NULL,
  contact_num INTEGER NULL,
  skills VARCHAR NULL,
  school_names VARCHAR NULL,
  degrees VARCHAR NULL,
  fields VARCHAR NULL,
  company_names VARCHAR NULL,
  createdbyid VARCHAR NULL,
  modifiedon TIMESTAMP NULL,
  updatedbyid VARCHAR NULL,
  work_authorization_status VARCHAR NULL,
  document_file_name VARCHAR NULL,
  document_content_type VARCHAR NULL,
  document_file_size INTEGER NULL,
  document_updated_at TIMESTAMP NULL,
  top_one_percent_status BOOLEAN NULL,
  top_five_percent_status BOOLEAN NULL,
  top_ten_percent_status BOOLEAN NULL,
  status VARCHAR NULL,
  recruiter_update_id INTEGER NULL,
  recently_added BOOLEAN NULL,
  active_date_at TIMESTAMP NULL,
  active_set_by_user_id INTEGER NULL,
  inbound_user_id INTEGER NULL,
  phone_number_id INTEGER NULL,
  person_id INTEGER NULL,
  remote_interest VARCHAR NULL,
  position_interest VARCHAR NULL,
  experience_years INTEGER NULL,
  supervising_num INTEGER NULL,
  salary_expectations VARCHAR NULL,
  job_search_stage VARCHAR NULL,
  position_desc VARCHAR NULL,
  visa_status BOOLEAN NULL,
  avatar_file_name VARCHAR NULL,
  avatar_content_type VARCHAR NULL,
  avatar_file_size INTEGER NULL,
  avatar_updated_at TIMESTAMP NULL,
  latest_pinned_note TEXT NULL,
  sms_last_from_user_id INTEGER NULL,
  github_url VARCHAR NULL,
  stack_overflow_url VARCHAR NULL,
  personal_site VARCHAR NULL,
  personal_site_available BOOLEAN NULL,
  stack_overflow_url_available BOOLEAN NULL,
  public_profile_url JSON NULL,
  api_standard_profile_request JSON NULL,
  industry JSON NULL,
  current_share JSON NULL,
  num_connections JSON NULL,
  num_connections_capped JSON NULL,
  summary JSON NULL,
  specialties JSON NULL,
  positions JSON NULL,
  picture_url JSON NULL,
  site_standard_profile_request JSON NULL,
  lever_candidate_id VARCHAR NULL,
  company_position_id INTEGER NULL,
  linkedin_profile_id INTEGER NULL,
  email_address_id INTEGER NULL,
  linkedin_field_of_study_id INTEGER NULL,
  linkedin_industry_id INTEGER NULL,
  linkedin_profile_education_id INTEGER NULL,
  linkedin_profile_position_id INTEGER NULL,
  linkedin_profile_publication_id INTEGER NULL,
  linkedin_profile_recommendation_id INTEGER NULL,
  linkedin_profile_url_resource_id INTEGER NULL,
  linkedin_school_id INTEGER NULL,
  education_level INTEGER NULL,
  public BOOLEAN NULL,
  attached_document_file_name VARCHAR NULL,
  attached_document_content_type VARCHAR NULL,
  attached_document_file_size INTEGER NULL,
  attached_document_updated_at TIMESTAMP NULL,
  message_date TIME NULL,
  top_company BOOLEAN NULL,
  top_school BOOLEAN NULL,
  tags VARCHAR NULL,
  original VARCHAR NULL,
  resume_text TEXT NULL,
  applied_to_all_jobs TIMESTAMP NULL,
  links TEXT NULL,
  organization_id UUID NULL,
  sourcer_id INTEGER NULL,
  linkedin_applicant_id BIGINT NULL DEFAULT 0,
  source VARCHAR NULL,
  collector_id INTEGER NULL DEFAULT 0,
  origin VARCHAR NULL,
  discarded_at TIMESTAMP NULL,
  cv_url TEXT[] NULL,
  currency TEXT NULL,
  tech_group TEXT NULL,
  role INTEGER NULL DEFAULT 0,
  parse_resume_json TEXT NULL,
  agency_id INTEGER NULL DEFAULT 0,
  portfolio VARCHAR NULL,
  "authorization" VARCHAR NULL,
  transfer VARCHAR NULL,
  state VARCHAR NULL,
  compensation VARCHAR NULL,
  sponsorship VARCHAR NULL,
  auto_submission INTEGER NULL DEFAULT 0,
  auto_sign_agreement INTEGER NULL DEFAULT 0,
  colour_id INTEGER NULL DEFAULT 0,
  match_job_process INTEGER NULL DEFAULT 0,
  experiences VARCHAR NULL,
  locations VARCHAR NULL,
  job_titles VARCHAR NULL,
  certificates TEXT NULL,
  education_degrees TEXT NULL,
  education_universitys TEXT NULL,
  company_worked TEXT NULL,
  designation_lists TEXT NULL,
  resume_reparse_at TIMESTAMP NULL,
  skill_match TEXT NULL,
  screening_inc TEXT NULL,
  highlight_inc TEXT NULL
);

CREATE INDEX IF NOT EXISTS idx_people_user_id ON people(user_id);
CREATE INDEX IF NOT EXISTS idx_people_discarded_at ON people(discarded_at);
CREATE INDEX IF NOT EXISTS idx_people_email_address ON people(email_address);

-- Notes table
CREATE TABLE IF NOT EXISTS notes (
  id SERIAL PRIMARY KEY,
  body TEXT NULL,
  person_id INTEGER NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  user_id INTEGER NULL,
  organization_id VARCHAR NULL,
  mention_ids INTEGER[] NULL DEFAULT '{}',
  discarded_at TIMESTAMP NULL,
  job_id INTEGER NULL,
  entity_type VARCHAR NULL DEFAULT 'memo'
);

CREATE INDEX IF NOT EXISTS idx_notes_discarded_at ON notes(discarded_at);
CREATE INDEX IF NOT EXISTS idx_notes_person_id ON notes(person_id);
CREATE INDEX IF NOT EXISTS idx_notes_user_id ON notes(user_id);

-- Identities table (references users)
CREATE TABLE IF NOT EXISTS identities (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NULL,
  provider VARCHAR NULL,
  uid VARCHAR NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_identities_user_id ON identities(user_id);

-- Add FK from identities to users (users already exists)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'identities_user_id_fkey'
  ) THEN
    ALTER TABLE identities
      ADD CONSTRAINT identities_user_id_fkey
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE NO ACTION;
  END IF;
END $$;
