-- Migration: Add jobs columns from production
-- Brings local jobs table in line with production by adding columns that exist
-- in production but were missing from the initial schema.
-- Uses ADD COLUMN IF NOT EXISTS for idempotency (e.g. autopilot_sourcing,
-- target_count may already exist from 012_add_autopilot_fields_to_jobs.sql).

ALTER TABLE jobs ADD COLUMN IF NOT EXISTS applicant_mu DOUBLE PRECISION NULL;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS applicant_stdev DOUBLE PRECISION NULL;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS prefered_top_schools TEXT NULL;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS rate VARCHAR NULL;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS job_website VARCHAR NULL;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS job_import VARCHAR NULL;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS unlisted_job INTEGER NULL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS compnay_logo_url VARCHAR NULL;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS decision_maker_name VARCHAR NULL;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS decision_maker_email VARCHAR NULL;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS link_origin_job TEXT NULL;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS agency_name VARCHAR NULL;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS agent_name VARCHAR NULL;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS date_applied VARCHAR NULL;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS ats_page_url_link VARCHAR NULL;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS company_career_page_url VARCHAR NULL;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS is_eligible_giftcard INTEGER NULL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS last_candidate_search_at TIMESTAMP NULL;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS in_mail_message_2 TEXT NULL;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS in_mail_message_3 TEXT NULL;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS in_mail_message_day_2 INTEGER NULL DEFAULT 1;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS in_mail_message_day_3 INTEGER NULL DEFAULT 1;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS work_type VARCHAR NULL;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS days_in_office INTEGER NULL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS distance VARCHAR NULL;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS autopilot_sourcing INTEGER NULL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS parsed_job_json TEXT NULL;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS target_count INTEGER NULL DEFAULT 0;
